import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { supabase } from '../src/lib/supabase';

type Product={id:string;name:string;description:string|null;product_category:string|null;product_variant:string|null;product_type:string|null;usage_types:string[]|null;quantity_value:number|null;quantity_unit:string|null;price:number;status:string};
const CATEGORIES=[['MILK','🥛 Milk'],['PANEER','🧀 Paneer'],['CURD','🥣 Curd'],['BUTTER','🧈 Butter'],['GHEE','🫙 Ghee'],['KHOYA_MAWA','🍮 Khoya/Mawa'],['CHICKEN','🍗 Chicken'],['MUTTON','🍖 Mutton'],['FISH','🐟 Fish'],['EGG','🥚 Eggs']];
const CHICKEN=[['LEG_PIECE','Leg Piece'],['BREAST_PIECE','Breast Piece'],['LIVER','Liver'],['WINGS','Wings'],['MIX_OF_EVERYTHING','Mix of Everything']];
const MUTTON=[['LEG_PIECE','Leg Piece'],['CURRY_CUT','Curry Cut'],['KEEMA','Keema'],['LIVER','Liver'],['MIX_OF_EVERYTHING','Mix of Everything']];
const FISH=[['ROHU','Rohu'],['KATLA','Katla'],['CURRY_CUT','Curry Cut'],['FILLET','Fillet'],['MIX_OF_EVERYTHING','Mixed Fish']];
const EGG=[['REGULAR','Regular Eggs'],['COUNTRY','Country Eggs'],['PREMIUM','Premium Eggs']];
export default function BusinessProductsScreen(){
 const[products,setProducts]=useState<Product[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const[name,setName]=useState('');const[category,setCategory]=useState('CHICKEN');const[variant,setVariant]=useState('');const[quantity,setQuantity]=useState('');const[unit,setUnit]=useState('G');const[price,setPrice]=useState('');const[business,setBusiness]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in again.');const{data:p,error:pe}=await supabase.from('dairywala_profiles').select('id,status').eq('owner_user_id',user.id).maybeSingle();if(pe)throw pe;if(!p||p.status!=='ACTIVE')throw new Error('Business must be ACTIVE before managing products.');const{data,error:e}=await supabase.from('products').select('id,name,description,product_category,product_variant,product_type,usage_types,quantity_value,quantity_unit,price,status').eq('dairywala_id',p.id).order('created_at',{ascending:false});if(e)throw e;setProducts((data||[]) as Product[])}catch(e){setError(e instanceof Error?e.message:'Unable to load products.')}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const variants=category==='CHICKEN'?CHICKEN:category==='MUTTON'?MUTTON:category==='FISH'?FISH:category==='EGG'?EGG:[['ORIGINAL','Original'],['MIXED','Mixed']];
 async function add(){const q=Number(quantity),pr=Number(price);if(!name.trim()||!category||!variant||!Number.isFinite(q)||q<=0||!unit.trim()||!Number.isFinite(pr)||pr<0){setError('Complete product, variant, quantity and price.');return}setSaving(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in again.');const{data:p}=await supabase.from('dairywala_profiles').select('id,status').eq('owner_user_id',user.id).maybeSingle();if(!p||p.status!=='ACTIVE')throw new Error('Business must be ACTIVE.');const usage=business?['BUSINESS']:['HOME'];const{error:e}=await supabase.from('products').insert({dairywala_id:p.id,name:name.trim(),description:null,product_category:category,product_variant:variant,product_type:null,usage_types:usage,quantity_value:q,quantity_unit:unit.trim().toUpperCase(),price:pr,status:'ACTIVE',bulk_order_enabled:business});if(e)throw e;setName('');setVariant('');setQuantity('');setPrice('');await load()}catch(e){setError(e instanceof Error?e.message:'Product could not be added.')}finally{setSaving(false)}}
 return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={false} onRefresh={load}/>}><Text style={styles.eyebrow}>BUSINESS</Text><Text style={styles.title}>Products & prices</Text><Text style={styles.muted}>Add dairy or meat products. Use one listing per package/weight so customer matching stays exact.</Text>{error?<Text style={styles.error}>{error}</Text>:null}
 <View style={styles.form}><Text style={styles.section}>Category</Text><View style={styles.options}>{CATEGORIES.map(([k,l])=><Pressable key={k} onPress={()=>{setCategory(k);setVariant('')}} style={[styles.option,category===k&&styles.selected]}><Text style={category===k?styles.selectedText:styles.optionText}>{l}</Text></Pressable>)}</View>
 <TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Listing name e.g. Fresh Chicken Leg Piece"/><Text style={styles.section}>Variant / Cut</Text><View style={styles.options}>{variants.map(([k,l])=><Pressable key={k} onPress={()=>setVariant(k)} style={[styles.option,variant===k&&styles.selected]}><Text style={variant===k?styles.selectedText:styles.optionText}>{l}</Text></Pressable>)}</View>
 <View style={styles.row}><TextInput style={[styles.input,styles.half]} value={quantity} onChangeText={setQuantity} placeholder="Weight / count" keyboardType="decimal-pad"/><TextInput style={[styles.input,styles.half]} value={unit} onChangeText={setUnit} placeholder="Unit"/></View><TextInput style={styles.input} value={price} onChangeText={setPrice} placeholder="Price ₹" keyboardType="decimal-pad"/>
 <Pressable onPress={()=>setBusiness(v=>!v)} style={styles.toggle}><Text style={styles.toggleText}>{business?'🍽️ Shop / Restaurant · Bulk enabled':'🏠 Home · Household listing'}</Text></Pressable>
 <Pressable style={styles.primary} disabled={saving||loading} onPress={add}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Add active product</Text>}</Pressable></View>
 <Text style={styles.section}>Your listings</Text>{loading?<ActivityIndicator/>:products.length===0?<Text style={styles.muted}>No products yet.</Text>:products.map(p=><View key={p.id} style={styles.card}><View style={styles.grow}><Text style={styles.product}>{p.name}</Text><Text style={styles.muted}>{p.product_category||'—'} · {p.product_variant||'—'} · {p.quantity_value} {p.quantity_unit} · ₹{Number(p.price).toFixed(2)}</Text></View><Text style={styles.status}>{p.status}</Text></View>)}</ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:24,paddingTop:56,paddingBottom:48},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:1.5,color:'#777'},title:{marginTop:8,fontSize:30,fontWeight:'800'},muted:{marginTop:5,color:'#777',lineHeight:20},error:{marginTop:14,color:'#b00020'},form:{marginTop:22,padding:18,borderWidth:1,borderColor:'#e5e5e5',borderRadius:15,marginBottom:24},section:{fontSize:18,fontWeight:'800',marginBottom:10},options:{gap:8,marginBottom:12},option:{minHeight:44,borderWidth:1,borderColor:'#ddd',borderRadius:11,justifyContent:'center',paddingHorizontal:12},selected:{backgroundColor:'#f5f5f5',borderColor:'#111'},optionText:{color:'#444'},selectedText:{fontWeight:'800'},input:{minHeight:50,borderWidth:1,borderColor:'#ddd',borderRadius:11,paddingHorizontal:14,fontSize:16,marginBottom:10},row:{flexDirection:'row',gap:10},half:{flex:1},toggle:{minHeight:48,borderRadius:11,borderWidth:1,borderColor:'#ddd',justifyContent:'center',paddingHorizontal:14,marginBottom:10},toggleText:{fontWeight:'700'},primary:{minHeight:50,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'700'},card:{marginTop:10,padding:16,borderWidth:1,borderColor:'#e5e5e5',borderRadius:14,flexDirection:'row',alignItems:'center'},grow:{flex:1},product:{fontSize:17,fontWeight:'800'},status:{fontSize:11,fontWeight:'800'}});
