import { useLocalSearchParams, useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, View, ScrollView } from 'react-native';
import { useEffect, useState } from 'react';
import { supabase } from '../src/lib/supabase';

type Seller={id:string;businessName:string;locality:string|null;phone:string|null;avatar:string|null;morning:boolean;evening:boolean;products:{id:string;name:string;variant:string|null;quantityValue:number|null;quantityUnit:string|null;price:number;bulk:boolean}[]};

export default function MeatDiscoveryScreen(){
 const router=useRouter(); const p=useLocalSearchParams<{locality?:string;postalCode?:string;productCategory?:string;variant?:string;usage?:string;quantityValue?:string;quantityUnit?:string;bulkOnly?:string;subscriptionPlan?:string}>();
 const[rows,setRows]=useState<Seller[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{let mounted=true;(async()=>{try{
  const locality=String(p.locality||'').trim(), postal=String(p.postalCode||'').trim(), category=String(p.productCategory||'').toUpperCase(), variant=String(p.variant||'').toUpperCase(), usage=String(p.usage||'').toUpperCase();
  if(!locality&&!postal) throw new Error('Please set your location first.');
  let areaQuery=supabase.from('dairywala_service_areas').select('dairywala_id');
  if(postal) areaQuery=areaQuery.eq('postal_code',postal); else areaQuery=areaQuery.ilike('locality',locality);
  const{data:areas,error:ae}=await areaQuery;if(ae)throw ae;
  const ids=[...new Set((areas||[]).map(x=>x.dairywala_id))];if(!ids.length){if(mounted)setRows([]);return;}
  const{data:profiles,error:pe}=await supabase.from('dairywala_profiles').select('id,business_name,locality,phone,profile_avatar').in('id',ids).eq('status','ACTIVE');if(pe)throw pe;
  const activeIds=(profiles||[]).map(x=>x.id);if(!activeIds.length){if(mounted)setRows([]);return;}
  const{data:slots,error:se}=await supabase.from('dairywala_delivery_slots').select('dairywala_id,slot_code,active').in('dairywala_id',activeIds).eq('active',true);if(se)throw se;
  const{data:products,error:prode}=await supabase.from('products').select('id,dairywala_id,name,product_category,product_variant,usage_types,quantity_value,quantity_unit,price,bulk_order_enabled,status').in('dairywala_id',activeIds).eq('status','ACTIVE').eq('product_category',category).eq('product_variant',variant);if(prode)throw prode;
  const filtered=(products||[]).filter(x=>{const usages=(x.usage_types||[]).map((v:string)=>v.toUpperCase());if(usage&&!usages.includes(usage))return false;if(p.quantityValue&&Number(x.quantity_value)!==Number(p.quantityValue))return false;if(p.quantityUnit&&String(x.quantity_unit||'').toUpperCase()!==String(p.quantityUnit).toUpperCase())return false;if(p.bulkOnly==='true'&&!x.bulk_order_enabled)return false;return true;});
  const out= (profiles||[]).map(pr=>({id:pr.id,businessName:pr.business_name,locality:pr.locality,phone:pr.phone,avatar:pr.profile_avatar,morning:(slots||[]).some(s=>s.dairywala_id===pr.id&&s.slot_code==='MORNING'),evening:(slots||[]).some(s=>s.dairywala_id===pr.id&&s.slot_code==='EVENING'),products:filtered.filter(x=>x.dairywala_id===pr.id).map(x=>({id:x.id,name:x.name,variant:x.product_variant,quantityValue:x.quantity_value,quantityUnit:x.quantity_unit,price:Number(x.price),bulk:x.bulk_order_enabled}))})).filter(x=>x.products.length);
  if(mounted)setRows(out);
 }catch(e){if(mounted)setError(e instanceof Error?e.message:'Unable to load meat sellers.')}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[p.locality,p.postalCode,p.productCategory,p.variant,p.usage,p.quantityValue,p.quantityUnit,p.bulkOnly]);
 const descriptor=p.usage==='BUSINESS'?'Subscription · '+(p.subscriptionPlan||'Recurring supply'):'Home · '+String(p.quantityValue||'')+' '+String(p.quantityUnit||'');
 return <ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>AVAILABLE NEAR YOU</Text><Text style={styles.title}>{p.productCategory} · {p.variant?.replaceAll('_',' ')}</Text><Text style={styles.body}>{descriptor}</Text>
 {loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Checking local sellers…</Text></View>:error?<View style={styles.empty}><Text style={styles.emptyTitle}>Could not load sellers</Text><Text style={styles.body}>{error}</Text></View>:!rows.length?<View style={styles.empty}><Text style={styles.emptyTitle}>No matching sellers yet</Text><Text style={styles.body}>There is no active seller in this area with this exact product configuration yet.</Text></View>:rows.map(s=><View key={s.id} style={styles.card}><View style={styles.head}><Text style={styles.avatar}>{s.avatar||'👨'}</Text><View style={styles.grow}><Text style={styles.seller}>{s.businessName}</Text><Text style={styles.meta}>{s.locality||'Local seller'}</Text></View></View>{s.products.map(pr=><Pressable key={pr.id} style={styles.product} onPress={()=>router.push({pathname:'/product',params:{id:pr.id}})}><View style={styles.grow}><Text style={styles.productName}>{pr.name}</Text><Text style={styles.meta}>{pr.quantityValue} {pr.quantityUnit} · ₹{pr.price.toFixed(2)}</Text></View><Text style={styles.add}>View ›</Text></Pressable>)}<Text style={styles.slots}>{s.morning?'Morning ':''}{s.evening?'Evening':''}</Text></View>)}</ScrollView>;
}
const styles=StyleSheet.create({container:{padding:24,paddingTop:58,paddingBottom:48,backgroundColor:'#fff',flexGrow:1},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:1.5,color:'#777'},title:{marginTop:9,fontSize:29,fontWeight:'800'},body:{marginTop:7,color:'#666',lineHeight:21},center:{paddingTop:45,alignItems:'center',gap:10},muted:{color:'#777'},empty:{marginTop:25,padding:20,borderWidth:1,borderColor:'#e5e5e5',borderRadius:16},emptyTitle:{fontSize:18,fontWeight:'800'},card:{marginTop:14,padding:16,borderWidth:1,borderColor:'#e5e5e5',borderRadius:16},head:{flexDirection:'row',alignItems:'center'},avatar:{fontSize:30,marginRight:10},grow:{flex:1},seller:{fontSize:18,fontWeight:'800'},meta:{marginTop:4,color:'#777',fontSize:13},product:{marginTop:12,padding:13,borderRadius:12,backgroundColor:'#f7f7f7',flexDirection:'row',alignItems:'center'},productName:{fontSize:15,fontWeight:'800'},add:{fontWeight:'800'},slots:{marginTop:12,fontSize:12,color:'#666'}});
